import './globals.css';
import React from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className='bg-black'>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
